[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
size = 12.0

# Colors - Customized https://github.com/catppuccin/alacritty/blob/main/catppuccin-frappe.toml
[colors.primary]
background = "#3a3a3a"
foreground = "#d2d2d2"
dim_foreground = "#838ba7"
bright_foreground = "#d2d2d2"

[colors.cursor]
text = "#303446"
cursor = "#f2d5cf"

[colors.vi_mode_cursor]
text = "#303446"
cursor = "#babbf1"

[colors.search.matches]
foreground = "#303446"
background = "#a5adce"

[colors.search.focused_match]
foreground = "#303446"
background = "#a6d189"

[colors.footer_bar]
foreground = "#303446"
background = "#a5adce"

[colors.hints.start]
foreground = "#303446"
background = "#e5c890"

[colors.hints.end]
foreground = "#303446"
background = "#a5adce"

[colors.selection]
text = "#303446"
background = "#f2d5cf"

[colors.normal]
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"

[colors.bright]
black = "#626880"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#a5adce"

[[colors.indexed_colors]]
index = 16
color = "#ef9f76"

[[colors.indexed_colors]]
index = 17
color = "#f2d5cf"

# Alacritty key bindings to make Option/Alt+Arrow and Option/Alt+Letter match common Zsh shortcuts
[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb" # Sends ESC + b (^[b), so Option+Left = backward-word in Zsh

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf" # Sends ESC + f (^[f), so Option+Right = forward-word in Zsh

[[keyboard.bindings]]
key = "D"
mods = "Alt"
chars = "\u001bd" # Sends ESC + d (^[d), so Option+D = kill-word in Zsh
