[window]
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
size = 12.0

# Colors - https://github.com/olimorris/onedarkpro.nvim
[colors.primary]
background  = "#fafafa"
foreground  = "#6a6a6a"

[colors.normal]
black       = "#6a6a6a"
red         = "#e05661"
green       = "#1da912"
yellow      = "#eea825"
blue        = "#118dc3"
magenta     = "#9a77cf"
cyan        = "#56b6c2"
white       = "#fafafa"

[colors.bright]
black       = "#848484"
red         = "#e88189"
green       = "#25d717"
yellow      = "#f2bb54"
blue        = "#1caceb"
magenta     = "#b69ddc"
cyan        = "#7bc6d0"
white       = "#ffffff"

[colors.cursor]
text        = "CellBackground"
cursor      = "CellForeground" # syntax-cursor-color

[colors.selection]
text        = "CellForeground"
background  = "#bebebe"

# Alacritty key bindings to make Option/Alt+Arrow and Option/Alt+Letter match common Zsh shortcuts
[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb" # Sends ESC + b (^[b), so Option+Left = backward-word in Zsh

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf" # Sends ESC + f (^[f), so Option+Right = forward-word in Zsh

[[keyboard.bindings]]
key = "D"
mods = "Alt"
chars = "\u001bd" # Sends ESC + d (^[d), so Option+D = kill-word in Zsh
